### ISSUE TITLE
Completion Block not getting called

### ISSUE THREAD

**Issue by shikharmohan** [BlinkReceipt/blinkereceipt-ios#3]
@dpanzer I'm trying to integrate the BlinkEReceipt SDK and here's the steps I've followed. I'm unable to get the completion block called (NSLogs aren't firing, breakpoints aren't getting hit) when verifying the retailer or grabbing orders. Is there something I'm missing? I am using a Trial SDK key.

I included the frameworks via standalone method, not via Cocoapods. 

In my AppDelegate.m: 

```
  [BRScanManager sharedManager].licenseKey = @"MyLicenseKey";
  [BRAccountLinkingManager shared];
```

In my react native bridge, native module: 

```
#import <BlinkEReceiptStatic/BRAccountLinkingManager.h>
#import <BlinkEReceiptStatic/BREReceiptManager.h>

RCT_EXPORT_METHOD(linkAccount:(NSString *)username password:(NSString *)password callback:(RCTResponseSenderBlock)callback){

  BRAccountLinkingCredentials *creds = [BRAccountLinkingCredentials  new];

  creds.username = username;
  creds.password = password;
  creds.retailer = BRAccountLinkingRetailerAmazon; //set to the retailer you're linking

  [[BRAccountLinkingManager  shared] linkAccountWithCredentials:creds];

  [[BRAccountLinkingManager shared] verifyAccountForRetailer:BRAccountLinkingRetailerAmazon withCompletion:^(BRAccountLinkingError error, UIViewController * _Nullable vc) {
    UIViewController *viewController = [[[UIApplication sharedApplication] keyWindow] rootViewController];

    if (error == BRAccountLinkingErrorNone) {
      NSLog(@"Successfully linked account!");
    } else if (error == BRAccountLinkingErrorVerificationNeeded) {
      [viewController presentViewController:vc animated:YES completion:nil];
    } else if (error == BRAccountLinkingErrorVerificationCompleted) {
      [viewController dismissViewControllerAnimated:YES completion:nil];
    } else {
      //handle other errors + success case
      NSLog(@"Other error");
    }

  }];
}
```

**Comment by shikharmohan** [comment]
Completion Block also isn't getting called when I call `getEReceiptsWithCompletion`

**Comment by dpanzer** [comment]
Hi @shikharmohan - I believe the issue here is that you need a valid product intelligence license key as well, which you would set into the `[BRScanManager sharedManager].prodIntelKey` property. I will follow up via e-mail to discuss making this available.

**Comment by shivrajkumar** [comment]
@dpanzer I am stuck on the same issue, even after adding the `[BRScanManager sharedManager].prodIntelKey` property.
@shikharmohan Were you able to resolve this?
