### ISSUE TITLE
Missing Pods Libraries, i.e - dyld[9753]: Library not loaded: @rpath/ 

### ISSUE THREAD

**Issue by asifhabib** [BlinkReceipt/blinkereceipt-ios#4]
I added the framework `BlinkEReceiptStatic.framework` as a stand alone framework and also added `AccountLinking.framework` and `MailCore.framework`. But there was runtime error like in the your other libraries. 
Other library issue is attached. 

https://github.com/BlinkReceipt/blinkreceipt-ios/issues/36#issue-1194961124

**Comment by dpanzer** [comment]
Please see answer on other issue.
